import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { parseManualUserIds } from '../lib/campaignEnrollment'
import { CAMPAIGN_COUNTRIES, buildFilteredCampaignAudience } from '../lib/campaignAudience'
import { CAMPAIGN_CREATOR_TYPES, buildCampaignInsert, buildTieredLevels } from '../lib/campaignCreatorModel'
import { useLanguage } from '../contexts/LanguageContext'
import { CampaignInfoButton, CampaignGuideButton } from '../components/campaign/CampaignGuide'
import ChallengeCreator from '../components/campaign/ChallengeCreator'

const TIERS=['BLACK','DIAMOND','PLATINUM','GOLD','SILVER','BRONZE']
const COUNTRY_LABEL={MY:'🇲🇾 Malaysia',SG:'🇸🇬 Singapore',KH:'🇰🇭 Cambodia'}
const TYPE_INFO={gold_bar:['Deposit threshold → physical gold bar / gift','达到存款门槛 → 实体金条 / 礼品'],pct_reward:['Deposit amount × percentage cashback','存款金额 × 百分比返现'],fixed_reward:['Deposit threshold → fixed reward','达到存款门槛 → 固定奖励'],tiered_reward:['Different percentage reward by deposit tier','按存款区间给不同百分比'],dual_tier:['Deposit + turnover → Credit + WCash','存款 + 流水 → Credit + WCash'],leaderboard:['Top players by valid bet → rank rewards','按有效投注排名 → 名次奖励'],tiered_deposit_reward:['Multiple deposit milestones → fixed Credit at each level','多个存款级别 → 每级固定Credit'],challenge_trust:['Free credit first → personal turnover task → reviewed bonus + streak','先送信用额 → 个人流水任务 → 审核奖金 + 连续奖励'],challenge_rebate:['Deposit / turnover target → rebate % of turnover + streak','存款 / 流水目标 → 流水返水% + 连续奖励']}
const TYPE_LABEL_ZH={gold_bar:'🥇 金条奖励',pct_reward:'💰 百分比返利',fixed_reward:'🎁 固定奖励',tiered_reward:'📊 阶梯百分比返利',dual_tier:'🎯 存款 + 流水阶梯',leaderboard:'🏆 排行榜',tiered_deposit_reward:'🎁 阶梯存款奖励',challenge_trust:'💝 信任金挑战',challenge_rebate:'💰 返水挑战'}
const CREATOR_TYPES={challenge_trust:{label:'💝 Trust Credit Challenge',isNew:true},challenge_rebate:{label:'💰 Rebate Challenge',isNew:true},...CAMPAIGN_CREATOR_TYPES}
const isChallenge=t=>t==='challenge_trust'||t==='challenge_rebate'
const input={width:'100%',background:'var(--surface2)',border:'1px solid var(--border)',color:'var(--text)',padding:'8px 10px',borderRadius:7,boxSizing:'border-box',fontSize:13}
const btn={background:'var(--accent)',color:'#fff',border:'none',padding:'8px 16px',borderRadius:8,fontWeight:700,cursor:'pointer'}
const secondary={background:'var(--surface2)',color:'var(--text)',border:'1px solid var(--border)',padding:'8px 14px',borderRadius:7,fontWeight:700,cursor:'pointer'}
const panel={background:'var(--surface)',border:'1px solid var(--border)',borderRadius:12}
const defaultLevels=()=>[{level_code:'L1',level_name:'Level 1',deposit_threshold:'10000',reward_amount:'150',description:''},{level_code:'L2',level_name:'Level 2',deposit_threshold:'30000',reward_amount:'900',description:''},{level_code:'L3',level_name:'Level 3',deposit_threshold:'50000',reward_amount:'3000',description:''}]
const defaultTierPct=()=>[{min:'10000',max:'29999',pct:'1.5'},{min:'30000',max:'49999',pct:'3'},{min:'50000',max:'',pct:'6'}]
const defaultDual=()=>[{depositThreshold:'10000',turnoverThreshold:'50000',creditAmount:'200',wcashAmount:'200'}]

export default function CampaignsUnifiedCreator(){
 const {lang}=useLanguage()
 const T=(en,zh)=>lang==='zh'?zh:en
 const [open,setOpen]=useState(false),[players,setPlayers]=useState([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('')
 const [gamingLabels,setGamingLabels]=useState({})
 const [form,setForm]=useState({campaign_type:'pct_reward',campaign_name:'',campaign_code:'',countries:['MY'],tiers:[],player_type:'',manual:'',start_date:'',end_date:'',budget_rm:'',status:'draft',deposit_target:'50000',reward_pct:'6',reward_cap:'',reward_fixed:'3000',gold_bar_value:'3400',reward_delivery:'credit',reward_tiers:defaultTierPct(),dual_tiers:defaultDual(),min_valid_bet:'3000000',min_deposit_lb:'50000',leaderboard_metric:'turnover',top_n:'3',rank_rewards:[{rank:1,amount:'12000'},{rank:2,amount:'12000'},{rank:3,amount:'12000'}],levels:defaultLevels(),settlement_frequency:'total',payout_mode:'all'})
 const ids=parseManualUserIds(form.manual)
 const audience=useMemo(()=>buildFilteredCampaignAudience(players,form.countries,form.tiers,ids,form.player_type,gamingLabels),[players,form.countries,form.tiers,form.manual,form.player_type,gamingLabels])
 const tierCount=audience.filter(p=>p.enrollment_source==='tier'||p.enrollment_source==='both').length
 const manualCount=audience.filter(p=>p.enrollment_source==='manual'||p.enrollment_source==='both').length
 const bothCount=audience.filter(p=>p.enrollment_source==='both').length
 const missingCount=ids.filter(id=>!players.some(p=>String(p.username||'').trim().toLowerCase()===id.toLowerCase()&&p.is_excluded!==true)).length
 useEffect(()=>{const hideLegacyCreate=()=>document.querySelectorAll('button').forEach(b=>{if(b.dataset.unifiedCampaignCreate==='true')return;const text=(b.textContent||'').trim();if(text==='＋ New Campaign'||text==='+ New Campaign')b.style.display='none'});hideLegacyCreate();const obs=new MutationObserver(hideLegacyCreate);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[])
 useEffect(()=>{if(open){setMessage('');supabase.from('vip_members').select('id,username,full_name,tier,currency,phone,whatsapp,is_excluded').then(({data,error})=>{if(error)setMessage(error.message);else setPlayers(data||[])});supabase.from('player_gaming_labels').select('username,player_type,player_type_icon').order('snapshot_month',{ascending:false}).then(({data})=>{if(!data)return;const map={};data.forEach(r=>{if(!map[r.username])map[r.username]=r});setGamingLabels(map)})}},[open])
 function toggleList(key,value){setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value]}))}
 function setType(type){setForm(f=>({...f,campaign_type:type,reward_tiers:type==='tiered_reward'?defaultTierPct():f.reward_tiers,dual_tiers:type==='dual_tier'?defaultDual():f.dual_tiers,leaderboard_metric:type==='leaderboard'?(f.leaderboard_metric||'turnover'):'turnover'}))}
 function updateLevel(i,key,value){setForm(f=>{const levels=[...f.levels];levels[i]={...levels[i],[key]:value};return {...f,levels}})}
 function addLevel(){setForm(f=>({...f,levels:[...f.levels,{level_code:`L${f.levels.length+1}`,level_name:`Level ${f.levels.length+1}`,deposit_threshold:'',reward_amount:'',description:''}]}))}
 function updateTierPct(i,key,value){setForm(f=>{const a=[...f.reward_tiers];a[i]={...a[i],[key]:value};return {...f,reward_tiers:a}})}
 function updateDual(i,key,value){setForm(f=>{const a=[...f.dual_tiers];a[i]={...a[i],[key]:value};return {...f,dual_tiers:a}})}
 async function create(){
  if(!form.campaign_name.trim())return setMessage(T('Campaign name is required.','请填写活动名称。'))
  if(!form.countries.length)return setMessage(T('Select at least one country/platform.','请至少选择一个国家/平台。'))
  if(!form.tiers.length)return setMessage(T('Select at least one VIP tier.','请至少选择一个VIP等级。'))
  if(!form.start_date||!form.end_date)return setMessage(T('Start date and end date are required.','请填写开始与结束日期。'))
  if(form.campaign_type==='tiered_deposit_reward'&&(!form.levels.length||form.levels.some(l=>Number(l.deposit_threshold)<=0||Number(l.reward_amount)<=0)))return setMessage(T('Every Tiered Deposit Reward level needs a valid deposit and Credit.','每个阶梯级别都需要有效的存款与Credit。'))
  if(form.campaign_type==='leaderboard'&&!['turnover','deposit','turnover_deposit'].includes(form.leaderboard_metric))return setMessage(T('Select a valid leaderboard metric.','请选择有效的排行榜指标。'))
  setLoading(true);setMessage('')
  try{
   const code=form.campaign_code.trim()||form.campaign_name.trim().toUpperCase().replace(/\s+/g,'-').slice(0,20)
   const base=buildCampaignInsert({campaign_type:form.campaign_type,campaign_name:form.campaign_name,campaign_code:code,countries:form.countries,tiers:form.tiers,manualUserIds:ids,payout_mode:form.payout_mode})
   const row={...base,platform:form.countries.length===1?form.countries[0]:'BOTH',start_date:form.start_date,end_date:form.end_date,budget_rm:form.budget_rm?Number(form.budget_rm):null,status:form.status,created_at:new Date().toISOString(),deposit_target:form.campaign_type==='leaderboard'||form.campaign_type==='dual_tier'?null:Number(form.deposit_target)||50000,reward_pct:form.campaign_type==='pct_reward'?Number(form.reward_pct)||0:null,reward_cap:form.reward_cap?Number(form.reward_cap):null,reward_fixed:['fixed_reward','tiered_deposit_reward'].includes(form.campaign_type)?Number(form.reward_fixed)||0:null,gold_bar_value:form.campaign_type==='gold_bar'?Number(form.gold_bar_value)||0:null,reward_delivery:form.reward_delivery||'credit',reward_tiers:form.campaign_type==='tiered_reward'?form.reward_tiers:form.campaign_type==='dual_tier'?form.dual_tiers:null,min_valid_bet:form.campaign_type==='leaderboard'?Number(form.min_valid_bet)||0:null,min_deposit_lb:form.campaign_type==='leaderboard'?Number(form.min_deposit_lb)||0:null,leaderboard_metric:form.campaign_type==='leaderboard'?form.leaderboard_metric:'turnover',top_n:form.campaign_type==='leaderboard'?Number(form.top_n)||3:null,rank_rewards:form.campaign_type==='leaderboard'?form.rank_rewards:null,settlement_frequency:form.campaign_type==='dual_tier'?form.settlement_frequency:null,requires_period_deposit:true,max_levels:form.campaign_type==='tiered_deposit_reward'?form.levels.length:null}
   const {data:campaign,error}=await supabase.from('campaigns').insert(row).select().single();if(error)throw error
   if(form.campaign_type==='tiered_deposit_reward'){const levels=buildTieredLevels(form.levels).map(l=>({...l,campaign_id:campaign.id}));const {error:levelError}=await supabase.from('campaign_levels').insert(levels);if(levelError)throw levelError}
   if(audience.length){const rows=audience.map(v=>({campaign_id:campaign.id,vip_id:v.id,username:v.username,tier:v.tier,player_name:v.full_name||null,whatsapp:v.whatsapp||v.phone||null,total_deposit:0,campaign_period_deposit:0,converted:false,payout_status:'pending',status:'enrolled',enrollment_source:v.enrollment_source,added_at:new Date().toISOString(),enrolled_at:new Date().toISOString()}));const {error:playerError}=await supabase.from('campaign_players').upsert(rows,{onConflict:'campaign_id,username'});if(playerError)throw playerError}
   setOpen(false);setMessage(T(`Created ${form.campaign_name}. ${audience.length} players enrolled.`,`已创建 ${form.campaign_name}，加入 ${audience.length} 位玩家。`));window.dispatchEvent(new CustomEvent('campaign-created'));window.setTimeout(()=>window.location.reload(),250)
  }catch(e){setMessage(T('Campaign creation failed: ','创建活动失败：')+e.message)}finally{setLoading(false)}
 }
 return <>
  <div style={{...panel,padding:'14px 18px',marginBottom:18,display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><div style={{fontSize:15,fontWeight:800}}>🎯 {T('Campaign Targeting','活动目标设定')}</div><div style={{fontSize:11,color:'var(--muted)',marginTop:3}}>{T('One campaign creator · Country + VIP Tier + Manual User ID targeting.','统一活动创建 · 国家 + VIP等级 + 手动用户ID')}</div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><CampaignGuideButton /><button data-unified-campaign-create="true" style={btn} onClick={()=>setOpen(true)}>＋ {T('New Campaign','新建活动')}</button></div></div>
  {open&&<div style={{position:'fixed',inset:0,zIndex:1300,background:'rgba(0,0,0,.72)',display:'flex',alignItems:'center',justifyContent:'center',padding:16}}><div style={{...panel,width:'100%',maxWidth:980,maxHeight:'94vh',overflowY:'auto'}}>
   <div style={{padding:'18px 22px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div><div style={{fontSize:18,fontWeight:800}}>📣 {T('New Campaign','新建活动')}</div><div style={{fontSize:11,color:'var(--muted)',marginTop:3}}>{T('Choose the campaign type, then configure its reward and audience in the same place. Click ⓘ to see how each type works.','选择活动类型，然后在同一页设定奖励与受众。点击 ⓘ 查看每种类型的说明。')}</div></div><button style={secondary} onClick={()=>setOpen(false)}>×</button></div>
   <div style={{padding:'18px 22px'}}>
    <div style={{fontSize:11,color:'var(--muted)',fontWeight:800,marginBottom:8}}>{T('CAMPAIGN TYPE *','活动类型 *')}</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8,marginBottom:16}}>{Object.entries(CREATOR_TYPES).map(([type,info])=><button type="button" key={type} onClick={()=>setType(type)} style={{textAlign:'left',padding:'11px 12px',borderRadius:9,border:`2px solid ${form.campaign_type===type?'var(--accent)':'var(--border)'}`,background:form.campaign_type===type?'rgba(255,106,0,.1)':'var(--surface2)',color:'var(--text)',cursor:'pointer',position:'relative'}}><div style={{display:'flex',alignItems:'center',gap:6}}><div style={{fontWeight:800,fontSize:12,flex:1}}>{lang==='zh'?(TYPE_LABEL_ZH[type]||info.label):info.label}{info.isNew&&<span style={{marginLeft:6,fontSize:9,fontWeight:800,padding:'1px 6px',borderRadius:8,background:'#f472b6',color:'#fff'}}>{T('NEW','新')}</span>}</div><CampaignInfoButton typeKey={type} /></div><div style={{fontSize:10,color:'var(--muted)',marginTop:3}}>{TYPE_INFO[type]?(lang==='zh'?TYPE_INFO[type][1]:TYPE_INFO[type][0]):''}</div></button>)}</div>
    {isChallenge(form.campaign_type)?<ChallengeCreator key={form.campaign_type} mode={form.campaign_type==='challenge_rebate'?'rebate':'trust_credit'} onCancel={()=>setOpen(false)} onCreated={(camp,n)=>{setOpen(false);setMessage(T(`Created ${camp.campaign_name}. ${n} players enrolled.`,`已创建 ${camp.campaign_name}，加入 ${n} 位玩家。`));window.dispatchEvent(new CustomEvent('campaign-created'));window.setTimeout(()=>window.location.reload(),250)}} />:<>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'10px 14px'}}>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('CAMPAIGN NAME *','活动名称 *')}</div><input style={input} value={form.campaign_name} onChange={e=>setForm(f=>({...f,campaign_name:e.target.value}))}/></div>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('CAMPAIGN CODE','活动代码')}</div><input style={input} value={form.campaign_code} onChange={e=>setForm(f=>({...f,campaign_code:e.target.value.toUpperCase()}))}/></div>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('START DATE *','开始日期 *')}</div><input type="date" style={input} value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))}/></div>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('END DATE *','结束日期 *')}</div><input type="date" style={input} value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))}/></div>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('STATUS','状态')}</div><select style={input} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{['draft','active','paused','ended'].map(x=><option key={x}>{x}</option>)}</select></div>
      <div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('BUDGET (RM)','预算 (RM)')}</div><input type="number" style={input} value={form.budget_rm} onChange={e=>setForm(f=>({...f,budget_rm:e.target.value}))}/></div>
    </div>
    <div style={{marginTop:14,paddingTop:14,borderTop:'1px solid var(--border)'}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800,marginBottom:7}}>{T('COUNTRY / PLATFORM — MULTI SELECT *','国家 / 平台 — 可多选 *')}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{CAMPAIGN_COUNTRIES.map(c=><button type="button" key={c} onClick={()=>toggleList('countries',c)} style={{...secondary,padding:'6px 12px',borderColor:form.countries.includes(c)?'var(--accent)':'var(--border)',background:form.countries.includes(c)?'rgba(255,106,0,.12)':'var(--surface2)'}}>{COUNTRY_LABEL[c]}</button>)}</div></div>
    <div style={{marginTop:14}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800,marginBottom:7}}>{T('VIP TIERS — MULTI SELECT *','VIP等级 — 可多选 *')}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{TIERS.map(t=><button type="button" key={t} onClick={()=>toggleList('tiers',t)} style={{...secondary,padding:'6px 12px',borderColor:form.tiers.includes(t)?'var(--accent)':'var(--border)',background:form.tiers.includes(t)?'rgba(255,106,0,.12)':'var(--surface2)'}}>{t}</button>)}</div></div>
    <div style={{marginTop:14}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800,marginBottom:7}}>{T('🎮 PLAYER TYPE FILTER — OPTIONAL','🎮 玩家类型筛选 — 可选')}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{[['',T('All Player Types','全部玩家类型')],['Slots King','🎰 Slots King'],['Live Casino VIP','🎲 Live Casino VIP'],['Sports Punter','⚽ Sports Punter'],['Slots + Live','🎰🎲 Slots + Live'],['Live + Sports','🎲⚽ Live + Sports'],['Multi-Platform','🎯 Multi-Platform'],['Casual','🃏 Casual']].map(([val,label])=><button type="button" key={val} onClick={()=>setForm(f=>({...f,player_type:val}))} style={{...secondary,padding:'6px 12px',borderColor:form.player_type===val?'rgba(139,92,246,.7)':'var(--border)',background:form.player_type===val?'rgba(139,92,246,.15)':'var(--surface2)',color:form.player_type===val?'#a78bfa':'var(--text)'}}>{label}</button>)}</div>{form.player_type&&<div style={{marginTop:6,fontSize:11,color:'var(--muted)'}}>{T('Only players with gaming profile matching','只包含游戏类型为')} <strong style={{color:'#a78bfa'}}>{form.player_type}</strong> {T('will be included. Players without a gaming profile are excluded.','的玩家。没有游戏档案的玩家会被排除。')}</div>}</div>
    {form.campaign_type!=='leaderboard'&&<div style={{marginTop:14}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800}}>{T('DEPOSIT TARGET','存款目标')}</div><input type="number" style={{...input,marginTop:5}} value={form.deposit_target} onChange={e=>setForm(f=>({...f,deposit_target:e.target.value}))}/></div>}
    <div style={{marginTop:14,paddingTop:14,borderTop:'1px solid var(--border)'}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800,marginBottom:8}}>{T('TYPE-SPECIFIC SETTINGS','类型专属设定')}</div>
      {form.campaign_type==='pct_reward'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><div style={{fontSize:10,color:'var(--muted)'}}>{T('REWARD %','奖励 %')}</div><input type="number" style={input} value={form.reward_pct} onChange={e=>setForm(f=>({...f,reward_pct:e.target.value}))}/></div><div><div style={{fontSize:10,color:'var(--muted)'}}>{T('MAX REWARD CAP','奖励上限')}</div><input type="number" style={input} value={form.reward_cap} onChange={e=>setForm(f=>({...f,reward_cap:e.target.value}))}/></div></div>}
      {form.campaign_type==='fixed_reward'&&<div><div style={{fontSize:10,color:'var(--muted)'}}>{T('FIXED REWARD','固定奖励')}</div><input type="number" style={input} value={form.reward_fixed} onChange={e=>setForm(f=>({...f,reward_fixed:e.target.value}))}/></div>}
      {form.campaign_type==='gold_bar'&&<div><div style={{fontSize:10,color:'var(--muted)'}}>{T('GOLD BAR / GIFT VALUE','金条 / 礼品价值')}</div><input type="number" style={input} value={form.gold_bar_value} onChange={e=>setForm(f=>({...f,gold_bar_value:e.target.value}))}/></div>}
      {form.campaign_type==='tiered_reward'&&<div style={{display:'grid',gap:7}}>{form.reward_tiers.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 90px 30px',gap:7}}><input type="number" style={input} value={x.min} placeholder="Min" onChange={e=>updateTierPct(i,'min',e.target.value)}/><input type="number" style={input} value={x.max} placeholder="Max" onChange={e=>updateTierPct(i,'max',e.target.value)}/><input type="number" style={input} value={x.pct} placeholder="%" onChange={e=>updateTierPct(i,'pct',e.target.value)}/><button style={secondary} onClick={()=>setForm(f=>({...f,reward_tiers:f.reward_tiers.filter((_,j)=>j!==i)}))}>×</button></div>)}<button style={secondary} onClick={()=>setForm(f=>({...f,reward_tiers:[...f.reward_tiers,{min:'',max:'',pct:''}]}))}>{T('＋ Add Tier','＋ 新增级别')}</button></div>}
      {form.campaign_type==='dual_tier'&&<div style={{display:'grid',gap:7}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr 30px',gap:7}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('MIN DEPOSIT (RM)','最低存款 (RM)')}</div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('MIN TURNOVER (RM)','最低流水 (RM)')}</div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('CREDIT (RM)','CREDIT (RM)')}</div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{T('WCASH (RM)','WCASH (RM)')}</div><div/></div>{form.dual_tiers.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr 30px',gap:7}}><input type="number" style={input} value={x.depositThreshold} placeholder="e.g. 10000" onChange={e=>updateDual(i,'depositThreshold',e.target.value)}/><input type="number" style={input} value={x.turnoverThreshold} placeholder="e.g. 50000" onChange={e=>updateDual(i,'turnoverThreshold',e.target.value)}/><input type="number" style={input} value={x.creditAmount} placeholder="e.g. 200" onChange={e=>updateDual(i,'creditAmount',e.target.value)}/><input type="number" style={input} value={x.wcashAmount} placeholder="e.g. 200" onChange={e=>updateDual(i,'wcashAmount',e.target.value)}/><button style={secondary} onClick={()=>setForm(f=>({...f,dual_tiers:f.dual_tiers.filter((_,j)=>j!==i)}))}>×</button></div>)}<button style={secondary} onClick={()=>setForm(f=>({...f,dual_tiers:[...f.dual_tiers,{depositThreshold:'',turnoverThreshold:'',creditAmount:'',wcashAmount:''}]}))}>{T('＋ Add Tier','＋ 新增级别')}</button></div>}
      {form.campaign_type==='leaderboard'&&<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>
        <div><div style={{fontSize:10,color:'var(--muted)'}}>{T('LEADERBOARD METRIC','排行榜指标')}</div><select style={input} value={form.leaderboard_metric} onChange={e=>setForm(f=>({...f,leaderboard_metric:e.target.value}))}><option value="turnover">{T('Turnover Race','流水竞赛')}</option><option value="deposit">{T('Deposit Race','存款竞赛')}</option><option value="turnover_deposit">{T('Turnover + Deposit Race','流水 + 存款竞赛')}</option></select></div>
        <div><div style={{fontSize:10,color:'var(--muted)'}}>{T('MIN VALID BET','最低有效投注')}</div><input type="number" style={input} value={form.min_valid_bet} onChange={e=>setForm(f=>({...f,min_valid_bet:e.target.value}))}/></div>
        <div><div style={{fontSize:10,color:'var(--muted)'}}>{T('MIN DEPOSIT','最低存款')}</div><input type="number" style={input} value={form.min_deposit_lb} onChange={e=>setForm(f=>({...f,min_deposit_lb:e.target.value}))}/></div>
        <div><div style={{fontSize:10,color:'var(--muted)'}}>{T('TOP N','前N名')}</div><input type="number" style={input} value={form.top_n} onChange={e=>setForm(f=>({...f,top_n:e.target.value}))}/></div>
      </div>}
      {form.campaign_type==='tiered_deposit_reward'&&<div style={{display:'grid',gap:10}}>
        <div style={{background:'var(--surface2)',border:'1px solid var(--border)',borderRadius:8,padding:'10px 12px'}}>
          <div style={{fontSize:10,color:'var(--muted)',fontWeight:800,marginBottom:8}}>{T('PAYOUT MODE','派彩模式')}</div>
          <div style={{display:'flex',gap:20}}>
            <label style={{display:'flex',alignItems:'center',gap:7,fontSize:13,cursor:'pointer'}}>
              <input type="radio" name="payout_mode" value="all" checked={form.payout_mode==='all'} onChange={()=>setForm(f=>({...f,payout_mode:'all'}))}/>
              <span><strong>{T('Pay all unlocked levels','派发所有已解锁级别')}</strong>{T(' — each level earns its own reward',' — 每级各自获得奖励')}</span>
            </label>
            <label style={{display:'flex',alignItems:'center',gap:7,fontSize:13,cursor:'pointer'}}>
              <input type="radio" name="payout_mode" value="highest_only" checked={form.payout_mode==='highest_only'} onChange={()=>setForm(f=>({...f,payout_mode:'highest_only'}))}/>
              <span><strong>{T('Pay highest level only','只派最高级别')}</strong>{T(' — one reward per player (the biggest)',' — 每位玩家只得一个（最高）奖励')}</span>
            </label>
          </div>
        </div>
        <div style={{display:'grid',gap:7}}>{form.levels.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'80px 1.2fr 1fr 1fr 30px',gap:7}}><input style={input} value={x.level_code} onChange={e=>setForm(f=>{const a=[...f.levels];a[i]={...a[i],level_code:e.target.value.toUpperCase()};return {...f,levels:a}})}/><input style={input} value={x.level_name} onChange={e=>updateLevel(i,'level_name',e.target.value)}/><input type="number" style={input} value={x.deposit_threshold} placeholder="Deposit ≥" onChange={e=>updateLevel(i,'deposit_threshold',e.target.value)}/><input type="number" style={input} value={x.reward_amount} placeholder="Credit" onChange={e=>updateLevel(i,'reward_amount',e.target.value)}/><button style={secondary} onClick={()=>setForm(f=>({...f,levels:f.levels.filter((_,j)=>j!==i)}))}>×</button></div>)}<button style={secondary} onClick={addLevel}>{T('＋ Add Level','＋ 新增级别')}</button></div>
      </div>}
    </div>
    <div style={{marginTop:14,paddingTop:14,borderTop:'1px solid var(--border)'}}><div style={{fontSize:10,color:'var(--muted)',fontWeight:800}}>{T('MANUAL USER IDs — OPTIONAL EXCEPTIONS','手动用户ID — 可选例外')}</div><textarea style={{...input,minHeight:64,marginTop:6,resize:'vertical',fontFamily:'inherit'}} value={form.manual} onChange={e=>setForm(f=>({...f,manual:e.target.value}))} placeholder={T('One User ID per line or comma-separated. Manual IDs bypass Country + Tier filters.','每行一个用户ID或用逗号分隔。手动ID不受国家与等级筛选限制。')}/></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:7,marginTop:12}}>{[[T('Tier','等级'),tierCount],[T('Manual','手动'),manualCount],[T('Both','两者'),bothCount],[T('Missing','找不到'),missingCount],[T('Final','最终'),audience.length]].map(([label,value])=><div key={label} style={{background:'var(--surface2)',border:'1px solid var(--border)',borderRadius:7,padding:'7px 9px'}}><div style={{fontSize:15,fontWeight:800}}>{value}</div><div style={{fontSize:9,color:'var(--muted)'}}>{label}</div></div>)}</div>
    {message&&<div style={{marginTop:10,color:message.includes('required')||message.includes('Select')||message.includes('failed')||message.includes('请')||message.includes('失败')?'#f85149':'#3fb950',fontSize:11}}>{message}</div>}
    <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button style={secondary} onClick={()=>setOpen(false)}>{T('Cancel','取消')}</button><button style={btn} disabled={loading} onClick={create}>{loading?T('Creating…','创建中…'):T('Create Campaign','创建活动')}</button></div>
    </>}
   </div>
  </div></div>}
 </>
}
