import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { calculateRate, getRetentionPriority, sumByCurrency } from '../lib/retention'
import { useLanguage } from '../contexts/LanguageContext'

const monthKey = (date) => { const d = new Date(date); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}` }
const previousMonth = (month) => { const [y,m] = month.split('-').map(Number); return monthKey(new Date(Date.UTC(y,m-2,1))) }
const nextMonth = (month) => { const [y,m] = month.split('-').map(Number); return monthKey(new Date(Date.UTC(y,m,1))) }
const formatAmount = (amount, currency) => `${currency || ''} ${Number(amount || 0).toLocaleString(undefined,{maximumFractionDigits:2})}`.trim()
const validPhone = value => String(value || '').replace(/\D/g,'').length >= 10
const whatsappLink = (v, hostName) => { const raw = validPhone(v.phone) ? v.phone : validPhone(v.whatsapp) ? v.whatsapp : ''; if (!raw) return null; const number = raw.replace(/\D/g,''); return `https://wa.me/${number}?text=${encodeURIComponent(`Hi ${v.username}, this is ${hostName || 'the VIP department'}.`)}` }

export default function RetentionWorkspace() {
  const navigate = useNavigate()
  const { t } = useLanguage()
  const [month,setMonth]=useState(monthKey(new Date())), [tier,setTier]=useState('ALL'), [view,setView]=useState('overview'), [hideReactivated,setHideReactivated]=useState(true)
  const [members,setMembers]=useState([]), [monthly,setMonthly]=useState([]), [contacts,setContacts]=useState([]), [reactivated,setReactivated]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
  useEffect(()=>{ let cancelled=false; async function load(){ setLoading(true);setError(''); const prev=previousMonth(month); const [a,b,c,d]=await Promise.all([
    supabase.from('vip_members').select('id,username,tier,currency,host_assigned,last_deposit_date,days_inactive,churn_risk,phone,whatsapp,is_excluded').eq('is_excluded',false),
    supabase.from('vip_monthly_totals').select('vip_id,username,snapshot_month,total_deposit,total_withdrawal,monthly_valid_bet,currency,tier,host_assigned').in('snapshot_month',[prev,month]),
    supabase.from('contact_logs').select('id,username,vip_id,outcome,notes,host_name,logged_at').gte('logged_at',`${month}-01T00:00:00`).lt('logged_at',`${nextMonth(month)}-01T00:00:00`),
    supabase.from('reactivation_logs').select('*').eq('reactivated_month',month).order('created_at',{ascending:false})
  ]); if(cancelled)return; const e=a.error||b.error||c.error||d.error; if(e){setError(e.message);setLoading(false);return} setMembers(a.data||[]);setMonthly(b.data||[]);setContacts(c.data||[]);setReactivated(d.data||[]);setLoading(false)} load();return()=>{cancelled=true}},[month])
  const data=useMemo(()=>{ const prev=previousMonth(month), map=new Map(); monthly.forEach(r=>{const key=r.vip_id||r.username;const p=map.get(key)||{id:key,username:r.username,tier:r.tier,currency:r.currency,host_assigned:r.host_assigned,prevDeposit:0,currentDeposit:0};if(r.snapshot_month===prev)p.prevDeposit=Number(r.total_deposit)||0;if(r.snapshot_month===month)p.currentDeposit=Number(r.total_deposit)||0;if(r.host_assigned)p.host_assigned=r.host_assigned;map.set(key,p)});members.forEach(m=>{if(!map.has(m.id))map.set(m.id,{id:m.id,username:m.username,tier:m.tier,currency:m.currency,host_assigned:m.host_assigned,prevDeposit:0,currentDeposit:0})});return [...map.values()].map(p=>{const m=members.find(x=>x.id===p.id||x.username===p.username);return {...p,phone:m?.phone,whatsapp:m?.whatsapp,retained:p.prevDeposit>0&&p.currentDeposit>0,reactivated:reactivated.some(r=>r.vip_id===p.id||r.username===p.username),days_inactive:m?.days_inactive||0,churn_risk:m?.churn_risk||''}}).filter(p=>tier==='ALL'||String(p.tier||'').toUpperCase()===tier)},[members,monthly,reactivated,month,tier])
  const previousActive=data.filter(p=>p.prevDeposit>0), retained=previousActive.filter(p=>p.currentDeposit>0), churned=previousActive.filter(p=>p.currentDeposit<=0&&(!hideReactivated||!p.reactivated)), atRisk=data.filter(p=>['HIGH','CRITICAL'].includes(String(p.churn_risk||'').toUpperCase())||p.days_inactive>=7), dormant=data.filter(p=>p.days_inactive>=30), contactedSet=new Set(contacts.map(c=>c.username||c.vip_id)), retentionRate=calculateRate(retained.length,previousActive.length), reactivationRate=calculateRate(reactivated.length,previousActive.length)
  const recovery=useMemo(()=>sumByCurrency(reactivated.map(r=>({currency:r.currency,amount:r.reactivation_deposit||r.deposit_amount||r.amount||0}))),[reactivated])
  const priorityRows=useMemo(()=>[...churned].sort((a,b)=>{const rank={CRITICAL:0,HIGH:1,MEDIUM:2,NORMAL:3};return (rank[getRetentionPriority(a)]??9)-(rank[getRetentionPriority(b)]??9)||(['DIAMOND','BLACK','PLATINUM'].includes(String(b.tier||'').toUpperCase())?1:0)-(['DIAMOND','BLACK','PLATINUM'].includes(String(a.tier||'').toUpperCase())?1:0)||b.days_inactive-a.days_inactive}),[churned])
  const hostStats=useMemo(()=>{const map=new Map();members.forEach(v=>{const h=v.host_assigned||'Unassigned';const e=map.get(h)||{host:h,assignedVips:0,reactivated:0,amounts:[]};e.assignedVips++;map.set(h,e)});reactivated.forEach(r=>{const h=r.host_name||'Unassigned';const e=map.get(h)||{host:h,assignedVips:0,reactivated:0,amounts:[]};e.reactivated++;e.amounts.push({currency:r.currency,amount:r.reactivation_deposit||r.deposit_amount||r.amount||0});map.set(h,e)});return [...map.values()].map(e=>({...e,rate:calculateRate(e.reactivated,e.assignedVips),recovered:sumByCurrency(e.amounts)})).sort((a,b)=>b.reactivated-a.reactivated)},[members,reactivated])
  if(loading)return <div className="p-8 text-sm opacity-60">{t('common.loading')}</div>
  if(error)return <div className="rounded-xl border p-6 text-sm">Unable to load retention data: {error}</div>
  const nav=[['overview',t('retention.overview')],['atRisk',t('retention.atRisk')],['followUp',t('retention.followUp')],['contacts',t('retention.contactLog')],['reactivated',t('retention.reactivated')]]
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-2xl font-semibold">📉 {t('retention.title')}</h1><p className="mt-1 text-sm opacity-70">{month}</p></div><div className="flex flex-wrap gap-2">{nav.map(([k,l])=><button key={k} onClick={()=>setView(k)} className={`rounded-lg px-3 py-2 text-sm ${view===k?'bg-blue-600 text-white':'border'}`}>{l}</button>)}<button onClick={()=>navigate('/retention-analytics')} className="rounded-lg border px-3 py-2 text-sm">{t('retention.analytics')}</button></div></div>
    <div className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><label className="text-sm">{t('common.month')}</label><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-lg border bg-transparent px-3 py-2"/><label className="text-sm">{t('common.tier')}</label><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-lg border bg-transparent px-3 py-2"><option value="ALL">{t('common.all')}</option><option value="GOLD">Gold</option><option value="PLATINUM">Platinum</option><option value="DIAMOND">Diamond</option><option value="BLACK">Black</option><option value="SILVER">Silver</option><option value="BRONZE">Bronze</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={hideReactivated} onChange={e=>setHideReactivated(e.target.checked)}/> Hide reactivated</label></div>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-5"><Kpi label={t('retention.atRiskVips')} value={atRisk.length}/><Kpi label={t('retention.highRisk')} value={data.filter(p=>['HIGH','CRITICAL'].includes(String(p.churn_risk||'').toUpperCase())).length}/><Kpi label={t('retention.dormant')} value={dormant.length}/><Kpi label={t('retention.contacted')} value={contactedSet.size}/><Kpi label={t('retention.reactivatedCount')} value={reactivated.length}/></div>
    {view==='overview'&&<><div className="grid grid-cols-1 gap-4 md:grid-cols-4"><Kpi label={t('retention.previousActive')} value={previousActive.length}/><Kpi label={t('retention.retained')} value={retained.length}/><Kpi label={t('retention.retentionRate')} value={`${retentionRate}%`}/><Kpi label={t('retention.reactivationRate')} value={`${reactivationRate}%`}/></div><MoneyCard values={recovery} title={t('retention.recoveredDeposit')}/><HostTable rows={hostStats} title={t('retention.hostPerformance')}/></>}
    {view==='atRisk'&&<ChurnTable rows={atRisk} title={t('retention.atRisk')} onOpen={id=>navigate(`/vips/${id}`)} onFollowUp={id=>navigate(`/follow-up?vip=${encodeURIComponent(id)}`)} hostName={''} t={t}/>} 
    {view==='followUp'&&<ChurnTable rows={priorityRows} title={t('retention.followUp')} onOpen={id=>navigate(`/vips/${id}`)} onFollowUp={id=>navigate(`/follow-up?vip=${encodeURIComponent(id)}`)} hostName={''} t={t}/>} 
    {view==='contacts'&&<ContactTable rows={contacts} t={t}/>} 
    {view==='reactivated'&&<ReactivationTable rows={reactivated} t={t}/>} 
  </div>
}
function Kpi({label,value}){return <div className="rounded-xl border p-5"><div className="text-xs uppercase tracking-wide opacity-60">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>}
function MoneyCard({values,title}){return <section className="rounded-xl border"><div className="border-b px-5 py-4 font-medium">{title}</div><div className="grid gap-3 p-5 md:grid-cols-3">{Object.entries(values).map(([c,a])=><div key={c} className="rounded-lg border p-4"><div className="text-xs opacity-60">{c}</div><div className="mt-1 text-xl font-semibold">{formatAmount(a,c)}</div></div>)}{!Object.keys(values).length&&<div className="text-sm opacity-60">—</div>}</div></section>}
function HostTable({rows,title}){return <section className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">{title}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">Host</th><th className="px-5 py-3">Assigned VIPs</th><th className="px-5 py-3">Reactivated</th><th className="px-5 py-3">Rate</th><th className="px-5 py-3">Recovered</th></tr></thead><tbody>{rows.map(r=><tr key={r.host} className="border-b last:border-0"><td className="px-5 py-3">{r.host}</td><td className="px-5 py-3">{r.assignedVips}</td><td className="px-5 py-3">{r.reactivated}</td><td className="px-5 py-3">{r.rate}%</td><td className="px-5 py-3">{Object.entries(r.recovered).map(([c,a])=><div key={c}>{formatAmount(a,c)}</div>)}</td></tr>)}</tbody></table></div></section>}
function ChurnTable({rows,title,onOpen,onFollowUp,hostName,t}){return <section className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">{title} <span className="ml-2 text-sm opacity-60">{rows.length}</span></div>{rows.length===0?<div className="p-8 text-center text-sm opacity-60">{t('retention.noRecords')}</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">{t('retention.player')}</th><th className="px-5 py-3">{t('retention.tier')}</th><th className="px-5 py-3">{t('retention.previousDeposit')}</th><th className="px-5 py-3">{t('retention.currentDeposit')}</th><th className="px-5 py-3">{t('retention.host')}</th><th className="px-5 py-3">{t('retention.priority')}</th><th className="px-5 py-3">{t('retention.action')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-5 py-3">{r.username}</td><td className="px-5 py-3">{r.tier}</td><td className="px-5 py-3">{formatAmount(r.prevDeposit,r.currency)}</td><td className="px-5 py-3">{formatAmount(r.currentDeposit,r.currency)}</td><td className="px-5 py-3">{r.host_assigned||'—'}</td><td className="px-5 py-3">{getRetentionPriority(r)}</td><td className="px-5 py-3"><div className="flex gap-2"><button className="rounded-md border px-2 py-1 text-xs" onClick={()=>onFollowUp(r.id)}>{t('retention.followUp')}</button><button className="rounded-md border px-2 py-1 text-xs" onClick={()=>onOpen(r.id)}>{t('retention.openVip')}</button>{whatsappLink(r,hostName)&&<a className="rounded-md border px-2 py-1 text-xs" href={whatsappLink(r,hostName)} target="_blank" rel="noopener noreferrer">WhatsApp</a>} {!whatsappLink(r,hostName)&&<span className="px-2 py-1 text-xs opacity-50" title={t('retention.noValidContact')}>WA —</span>}</div></td></tr>)}</tbody></table></div>}</section>}
function ContactTable({rows,t}){return <section className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">{t('retention.contactLog')} <span className="ml-2 text-sm opacity-60">{rows.length}</span></div>{rows.length===0?<div className="p-8 text-center text-sm opacity-60">{t('retention.noRecords')}</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">{t('retention.player')}</th><th className="px-5 py-3">Outcome</th><th className="px-5 py-3">Host</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Notes</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-5 py-3">{r.username}</td><td className="px-5 py-3">{r.outcome||'—'}</td><td className="px-5 py-3">{r.host_name||'—'}</td><td className="px-5 py-3">{r.logged_at?new Date(r.logged_at).toLocaleString():'—'}</td><td className="px-5 py-3">{r.notes||'—'}</td></tr>)}</tbody></table></div>}</section>}
function ReactivationTable({rows,t}){return <section className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">{t('retention.reactivated')} <span className="ml-2 text-sm opacity-60">{rows.length}</span></div>{rows.length===0?<div className="p-8 text-center text-sm opacity-60">{t('retention.noRecords')}</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">{t('retention.player')}</th><th className="px-5 py-3">{t('retention.tier')}</th><th className="px-5 py-3">{t('retention.daysInactive')}</th><th className="px-5 py-3">Host</th><th className="px-5 py-3">Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-5 py-3">{r.username}</td><td className="px-5 py-3">{r.tier||'—'}</td><td className="px-5 py-3">{r.days_was_inactive??'—'}</td><td className="px-5 py-3">{r.host_name||'—'}</td><td className="px-5 py-3">{r.created_at?new Date(r.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div>}</section>}
