import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { calculateRate, getRetentionPriority } from '../lib/retention'

const monthKey = (date) => { const d = new Date(date); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}` }
const previousMonth = (month) => { const [y,m] = month.split('-').map(Number); return monthKey(new Date(Date.UTC(y,m-2,1))) }
const formatAmount = (amount, currency) => `${currency || ''} ${Number(amount || 0).toLocaleString(undefined,{maximumFractionDigits:2})}`.trim()

export default function RetentionWorkspace() {
  const [month,setMonth]=useState(monthKey(new Date())), [tier,setTier]=useState('ALL'), [view,setView]=useState('overview'), [hideReactivated,setHideReactivated]=useState(true)
  const [members,setMembers]=useState([]), [monthly,setMonthly]=useState([]), [reactivated,setReactivated]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
  useEffect(()=>{ let cancelled=false; async function load(){ setLoading(true);setError(''); const prev=previousMonth(month); const [a,b,c]=await Promise.all([
    supabase.from('vip_members').select('id,username,tier,currency,host_assigned,last_deposit_date,days_inactive,churn_risk,is_excluded').eq('is_excluded',false),
    supabase.from('vip_monthly_totals').select('vip_id,username,snapshot_month,total_deposit,total_withdrawal,monthly_valid_bet,currency,tier,host_assigned').in('snapshot_month',[prev,month]),
    supabase.from('reactivation_logs').select('*').eq('reactivated_month',month).order('created_at',{ascending:false})
  ]); if(cancelled)return; const e=a.error||b.error||c.error; if(e){setError(e.message);setLoading(false);return} setMembers(a.data||[]);setMonthly(b.data||[]);setReactivated(c.data||[]);setLoading(false)} load();return()=>{cancelled=true}},[month])
  const data=useMemo(()=>{ const prev=previousMonth(month), map=new Map(); monthly.forEach(r=>{const key=r.vip_id||r.username;const p=map.get(key)||{id:key,username:r.username,tier:r.tier,currency:r.currency,host_assigned:r.host_assigned,prevDeposit:0,currentDeposit:0};if(r.snapshot_month===prev)p.prevDeposit=Number(r.total_deposit)||0;if(r.snapshot_month===month)p.currentDeposit=Number(r.total_deposit)||0;map.set(key,p)});members.forEach(m=>{if(!map.has(m.id))map.set(m.id,{id:m.id,username:m.username,tier:m.tier,currency:m.currency,host_assigned:m.host_assigned,prevDeposit:0,currentDeposit:0})});return [...map.values()].map(p=>({...p,retained:p.prevDeposit>0&&p.currentDeposit>0,reactivated:reactivated.some(r=>r.vip_id===p.id||r.username===p.username),days_inactive:members.find(m=>m.id===p.id)?.days_inactive||0,churn_risk:members.find(m=>m.id===p.id)?.churn_risk||''})).filter(p=>tier==='ALL'||String(p.tier||'').toUpperCase()===tier)},[members,monthly,reactivated,month,tier])
  const previousActive=data.filter(p=>p.prevDeposit>0), retained=previousActive.filter(p=>p.currentDeposit>0), churned=previousActive.filter(p=>p.currentDeposit<=0&&(!hideReactivated||!p.reactivated)), retentionRate=calculateRate(retained.length,previousActive.length)
  const tierStats=useMemo(()=>{const m=new Map();previousActive.forEach(p=>{const k=String(p.tier||'Unknown'),x=m.get(k)||{tier:k,previous:0,retained:0,churned:0};x.previous++;if(p.currentDeposit>0)x.retained++;else x.churned++;m.set(k,x)});return [...m.values()].map(x=>({...x,rate:calculateRate(x.retained,x.previous)})).sort((a,b)=>b.previous-a.previous)},[previousActive])
  if(loading)return <div className="p-8 text-sm opacity-60">Loading retention data…</div>
  if(error)return <div className="rounded-xl border p-6 text-sm">Unable to load retention data: {error}</div>
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-2xl font-semibold">📉 Monthly Churn</h1><p className="mt-1 text-sm opacity-70">上月有存款，本月至今未存款的玩家</p></div><div className="flex flex-wrap gap-2">{[['overview','Overview'],['churn','Churn List'],['reactivated','Reactivated']].map(([k,l])=><button key={k} onClick={()=>setView(k)} className={`rounded-lg px-3 py-2 text-sm ${view===k?'bg-blue-600 text-white':'border'}`}>{l}</button>)}</div></div>
    <div className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><label className="text-sm">Month</label><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-lg border bg-transparent px-3 py-2"/><label className="text-sm">Tier</label><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-lg border bg-transparent px-3 py-2"><option value="ALL">All Tiers</option><option value="GOLD">Gold</option><option value="PLATINUM">Platinum</option><option value="DIAMOND">Diamond</option><option value="BLACK">Black</option><option value="SILVER">Silver</option><option value="BRONZE">Bronze</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={hideReactivated} onChange={e=>setHideReactivated(e.target.checked)}/> Hide reactivated</label></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-4"><Kpi label="上月存款玩家" value={previousActive.length}/><Kpi label="本月流失" value={churned.length}/><Kpi label="本月留存" value={retained.length}/><Kpi label="Retention Rate" value={`${retentionRate}%`}/></div>
    {view==='overview'&&<><div className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">Tier Retention</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">Tier</th><th className="px-5 py-3">Previous</th><th className="px-5 py-3">Churned</th><th className="px-5 py-3">Retained</th><th className="px-5 py-3">Rate</th></tr></thead><tbody>{tierStats.map(x=><tr key={x.tier} className="border-b last:border-0"><td className="px-5 py-3">{x.tier}</td><td className="px-5 py-3">{x.previous}</td><td className="px-5 py-3">{x.churned}</td><td className="px-5 py-3">{x.retained}</td><td className="px-5 py-3">{x.rate}%</td></tr>)}</tbody></table></div></div></>}
    {view==='churn'&&<ChurnTable rows={churned}/>} {view==='reactivated'&&<ReactivationTable rows={reactivated}/>} 
  </div>
}
function Kpi({label,value}){return <div className="rounded-xl border p-5"><div className="text-xs uppercase tracking-wide opacity-60">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>}
function ChurnTable({rows}){return <div className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">玩家名单 <span className="ml-2 text-sm opacity-60">{rows.length}</span></div>{rows.length===0?<div className="p-8 text-center text-sm opacity-60">No churn players for the selected filters.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">Player</th><th className="px-5 py-3">Tier</th><th className="px-5 py-3">Previous Deposit</th><th className="px-5 py-3">Current Deposit</th><th className="px-5 py-3">Host</th><th className="px-5 py-3">Priority</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-5 py-3">{r.username}</td><td className="px-5 py-3">{r.tier}</td><td className="px-5 py-3">{formatAmount(r.prevDeposit,r.currency)}</td><td className="px-5 py-3">{formatAmount(r.currentDeposit,r.currency)}</td><td className="px-5 py-3">{r.host_assigned||'—'}</td><td className="px-5 py-3">{getRetentionPriority(r)}</td></tr>)}</tbody></table></div>}</div>}
function ReactivationTable({rows}){return <div className="overflow-hidden rounded-xl border"><div className="border-b px-5 py-4 font-medium">Reactivated <span className="ml-2 text-sm opacity-60">{rows.length}</span></div>{rows.length===0?<div className="p-8 text-center text-sm opacity-60">No reactivation records for this month.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="px-5 py-3">Player</th><th className="px-5 py-3">Tier</th><th className="px-5 py-3">Inactive Days</th><th className="px-5 py-3">Previous Deposit Date</th><th className="px-5 py-3">New Deposit Date</th><th className="px-5 py-3">Host</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-5 py-3">{r.username}</td><td className="px-5 py-3">{r.tier}</td><td className="px-5 py-3">{r.days_was_inactive??'—'}</td><td className="px-5 py-3">{r.prev_last_deposit||'—'}</td><td className="px-5 py-3">{r.new_deposit_date||'—'}</td><td className="px-5 py-3">{r.host_name||'—'}</td></tr>)}</tbody></table></div>}</div>}
